// Generated by CoffeeScript 1.9.0
(function() {
  var eventable, eventableOptions;

  eventable = require('events-ex/eventable');

  eventableOptions = require('./eventable-options');

  module.exports = function(aClass, aOptions) {
    return eventable(aClass, eventableOptions(aOptions));
  };

}).call(this);
