// Generated by CoffeeScript 1.12.7
(function() {
  var AbstractNosql;

  AbstractNosql = require('./abstract-nosql');

  AbstractNosql.prototype.$abilities = {
    Eventable: require('./eventable-options')
  };

  module.exports = AbstractNosql;

}).call(this);
